version: '3.5'
services:
  local:
    container_name: gmeet
    build: .
    image: gmeet:latest
    env_file:
      - env-variables.env
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND=${BACKEND:-gmail}
      - VIDEO_NAME=${VIDEO_NAME:-video}
      - MAX_DURATION=${MAX_DURATION:-7200}
      - MIN_DURATION=${MIN_DURATION:-1800}
      - ASK_JOIN=${ASK_JOIN:-True}
      - FRAC_TO_EXIT=${FRAC_TO_EXIT:-0.90}
      - RESOLUTION=${RESOLUTION:-1920x1080}
      - FAST=${FAST:-False}
    volumes:
      - ${OUTPUT_DIR:-./}:/output
    command: sh ./sources/driver.sh